-- github.com/hasanshanto
-- MS SQL SERVER

SELECT COUNTRY.CONTINENT, ROUND(AVG(CITY.POPULATION), 0)
FROM COUNTRY
INNER JOIN CITY
ON COUNTRY.CODE = CITY.COUNTRYCODE
GROUP BY COUNTRY.CONTINENT;
